spring.datasource.url: jdbc:mysql://127.0.0.1:33061/translator?useSSL=false&useUnicode=true&characterEncoding=utf-8
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.username: root
spring.datasource.password: 123

#spring.jpa.show-sql: true
#spring.jpa.properties.hibernate.format_sql: true
#spring.jpa.properties.hibernate.show_sql_comments: true

#spring.jpa.hibernate.ddl-auto: create
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring.servlet.multipart.max-file-size: 227MB
spring.servlet.multipart.max-request-size: 228MB

#debug: true

server.servlet.context-path: /translator
spring.mustache.suffix: .mu

jasypt.encryptor.password: ${ENCRYPT_KEY:}

oauth2:
  callback-url: /oauth2/callback?provider=
  providers:
    GitHub:
      client-id: ENC(o8HiGESL9g7VVUsQmwhK4ht80duLLWXOZjoN63BQDVwbqYidHNwLpbF+q4yHHVI7ftVhSLm6RXClcH4ttJGcJQ==)
      secret-key: ENC(HUDVO+RlVI46Czaf8FYIKm6jtIr6G6mKNQBM+++AhM8AmAhIwAuRCz+/P5TuIq/Tmv+OJB7c9IR/+MflYpR6uUwQorLD0fSceLnHUpFSkNU=)

menu:
  items:
  - id: UNKNOWN_WORDS
    title: Изучать
    url: /unknown-words
  - id: SOURCES
    title: Источники
    url: /sources
  - id: CLOUD
    title: Облако слов
    url: /cloud
  - id: ADMIN
    title: Админка
    role: Admin
    items:
      - id: UPLOAD
        title: Загрузить книгу
        url: /admin/upload-book
      - id: DEFINITION_LOG
        title: Определения слов
        url: /admin/definitions/log/last
      - id: NORMALIZATION
        title: Нормализация слов
        url: /admin/normalization
      - id: ETL
        title: Allitebooks log
        url: /admin/etl/download-process
      - id: EXPORT
        title: Экспорт слов пользователей
        url: /admin/export
      - id: IMPORT
        title: Импорт слов пользователей
        url: /admin/import
  - id: SETTINGS
    title: Настройки
    url: /user/settings